### ISSUE TITLE
Inquiry About EDEN Virtual Dataset Availability

### ISSUE THREAD

**Issue by yangcong1617** [lhoangan/eden-generation#4]
Hi,

I’m reaching out regarding the EDEN virtual dataset (previously hosted at https://lhoangan.github.io/eden/). The download link appears to be unavailable (returns 404).

Would you happen to have a backup copy of the dataset or an updated download link? If so, could you kindly share it? This dataset would be very helpful for my research.

Thank you for your time and any assistance you can provide!

Best regards

**Comment by lhoangan** [comment]
Hi, 

Thank you for your interest. There was a minor technical problem which has been resolved. They should be back by now.

Best regards,

**Comment by lbj000** [comment]
Hi,

I'm writing to follow up on the previous issue regarding the EDEN dataset.

I saw that the download link was reported to be fixed back in July, but I just tried to access it today and I'm still getting a 404 error. The dataset would be very valuable for my research, so I would really appreciate it if you could double-check the link or point me to an alternative download location.

If the dataset is no longer publicly hosted, could you let me know if there is another way to request access?

Thank you for your time and help.

Best regards,

**Comment by lhoangan** [comment]
Hi @lbj000, thanks for letting us know. It's fixed and now up and running.
